### ISSUE TITLE
极限测试时的 error: [Errno 10055] 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。 错误

### ISSUE THREAD

**Issue by GameXG** [GameXG/TcpRoute#12]
WARNING:root:[socks5] 远程代理服务器连接失败！ host:127.0.0.1 ,port:5555 ,timeout:1
WARNING:root:Traceback (most recent call last):
  File "D:/mpython/TcpRoute/tcpRoute.py", line 469, in __forward
    s = socket.create_connection((self.host,self.port),timeout)
  File "C:\Python27\lib\site-packages\gevent\socket.py", line 593, in create_connection
    raise err
error: [Errno 10055] 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。

http://www.cnblogs.com/eaglet/archive/2010/09/21/1832233.html

**Comment by GameXG** [comment]
http://phpbb-tw.net/phpbb/viewtopic.php?t=53619

虽然有半开连接数限制，但是现在还没碰到。

**Comment by GameXG** [comment]
https://support.microsoft.com/en-us/kb/969710
好吧，Windows Vista 之后就无半开连接数限制了。

**Comment by GameXG** [comment]
关闭
